title: Bastelherzen | Gebastelt mit Liebe
url: 
baseurl:
author: Bastelherzen
email: info@bastelherzen.de
description: >-
  Bastelherzen | Basteln mit Liebe!

# Build settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
